#!/bin/bash -e


# The motto: Checks if the current branch is master

CURRENT_BRANCH=`git cbr`

if [ $CURRENT_BRANCH != master ]
then
	echo "You must be on the master branch in order to run this command."
	exit 1
fi
