#!/bin/bash -e


# The motto: Some statistics about branch
# Description:

source $(dirname $0)/colors

git rev-parse -q --verify refs/heads/develop > /dev/null
if [ "$?" == "1" ]
then
	exit
fi

echo
header "Statistics for branch"
tab; git cbr

header "Commits by author:"
git log --pretty="%an" develop..|sort|uniq -c
header "Number of files were added:"
tab; git log --find-renames --name-status --diff-filter=A develop..|grep ^A\\b | wc -l
