#!/bin/bash -e


# The motto: Create a patch file holding current changes

filename=$1

if [ "$filename" == "" ]
then
	filename+=`pwgen 5 1`
fi
filename=`date +%FT%T`-$filename

git diff --no-prefix > tmp.$filename.patch
