#!/bin/bash -e

# The motto: Svn CommIt
# Commits to the SVN repository

git onmaster

# Save the updates, if any, since they prohibit us to make a commit
ID=`git stn`
git stash

git svn dcommit

if [ "$ID" != `git stn` ]
then
	# Restore the saved patch, if any
	git cont
fi

